id = "maparoni"
name = "Maparoni"
version = "0.1.0"
schema_version = 1
authors = ["Adrian Schoenig"]
description = "Formaggio pipeline language and Maparoni expression language support for Zed"

[grammars.formaggio]
repository = "file:///Users/adrian/Development/tree-sitter-formaggio"
rev = "09855a1b09dcb14389e13d370db9a3e9c7ee50c0"

[grammars.maparoni]
repository = "file:///Users/adrian/Development/tree-sitter-maparoni"
rev = "5ac59d4fc6835bf59b6dd9d3e9ed78d0c9025b39"
