id = "maparoni"
name = "Maparoni"
version = "0.1.0"
schema_version = 1
authors = ["Adrian Schoenig"]
description = "Formaggio pipeline language and Maparoni expression language support for Zed"

[grammars.formaggio]
repository = "file:///Users/adrian/Development/tree-sitter-formaggio"
rev = "1614f1be73327bf800fdfe3682ceab25488d6218"

[grammars.maparoni]
repository = "file:///Users/adrian/Development/tree-sitter-maparoni"
rev = "c30d5341bd820c26c31bdf7517792ca059b1542b"
